### ISSUE TITLE
Is this compatibile with the GOG version?

### ISSUE THREAD

**Issue by adolfintel** [KOTORCommunityPatches/TSL_Community_Patch#48]
I've installed this mod on the GOG version, which is different from the 2015 steam version and based on the original 2005 exe, and there were some warnings during the installation about missing files.

I was able to play anyway, but I noticed some minor glitches, for instance:
* When Mira enters the Jekk Jekk Tar, she's not wearing the pressure suit but everyone talks to her like she is
* Vogga's texture has transparency issues

So I was wondering if the current version is compatible with the GOG version, and if it's not, which mods you would recommend for it.

Thanks

**Comment by DarthParametric** [comment]
Missing files indicate that you did not install TSLRCM, or didn't install it first at least. In either event, your install (and saves) are toast. You'll need to scrap everything and start fresh from a clean install.

**Comment by adolfintel** [comment]
Is it mandatory to install TSLRCM? It's my first playthrough and I wanted to have just bug fixes

**Comment by DarthParametric** [comment]
Yes. It is mandatory for K2CP.

It is not advisable to ever not use TSLRCM regardless, since that fixes numerous bugs itself. You don't ever want to play the game in its vanilla state, since it's a broken mess. However, you do want to also install this - http://deadlystream.com/files/file/296-unofficial-tslrcm-tweak-pack/ - which mitigates some of TSLRCM's more dubious inclusions. Note that you must install TSLRCM before anything else, since it is a hard overwrite.

**Comment by adolfintel** [comment]
Aw shit, that's the third time I have to restart this game.
